Increases timeout for initial heartbeat from 30s to 120s
OpenStack slave could haeve a weird I/O pauses that sometimes cause the database to take a really long
time to start. Also note that the timeout is absolute, so eventhough the Thread sleep is 1s,
there could be as few as 4 attempts in the 30s window.

Furthermore, the commit fixes logging glitch:

```
SEVERE: DB not ready to answer the test statement: SELECT 1;. Remaining time: -1793, approx -1 attempts.
org.postgresql.util.PSQLException: FATAL: the database system is starting up
```

With ```... = Math.max(0, overallTimeoutMs - (System.currentTimeMillis() - timestamp));```